sudo: false
language: python
before_install:
  - >-
    curl -X POST -H "Content-Type: application/json" -H "Authorization: token
    $GITHUB_TOKEN" -d "{\"state\":\"pending\",\"description\":\"Dependent build
    created\",\"context\":\"continuous-integration/travis-ci/python-hooks-handler\",\"target_url\":\"https://travis-ci.org/apiaryio/dredd/builds/$TRAVIS_BUILD_ID\"}"
    'https://api.github.com/repos/apiaryio/dredd/statuses/659c3ba8476db3b3317a377a89b370fd35a8e2bc'
  - node --version
  - npm link --python=python2 ./__dredd__
  - bundle install
python: '3.5'
script:
  - python -B -m unittest discover
  - pip install -e .
  - bundle exec cucumber
env:
  global:
    secure: >-
      e7YKW17MjMUn42zsjEL3mN4lAyXp8Fz6NI5HdHCTh8RH0UnU13p7e8JkR7AaJaeFxRnsfSGF122/73nm+vn6XdK5KfdJSaa2s/Y8N3XOrFlnBDtWWxgMaw/geqgssRIv5kjEQSLoXybkVuPqmDATdKP2TG4UCb1XbeHOSzR6U4Q=
after_failure:
  - >-
    curl -X POST -H "Content-Type: application/json" -H "Authorization: token
    $GITHUB_TOKEN" -d "{\"state\":\"error\",\"description\":\"Dependent build
    finished\",\"context\":\"continuous-integration/travis-ci/python-hooks-handler\",\"target_url\":\"https://travis-ci.org/apiaryio/dredd/builds/$TRAVIS_BUILD_ID\"}"
    'https://api.github.com/repos/apiaryio/dredd/statuses/659c3ba8476db3b3317a377a89b370fd35a8e2bc'
after_success:
  - >-
    curl -X POST -H "Content-Type: application/json" -H "Authorization: token
    $GITHUB_TOKEN" -d "{\"state\":\"success\",\"description\":\"Dependent build
    finished\",\"context\":\"continuous-integration/travis-ci/python-hooks-handler\",\"target_url\":\"https://travis-ci.org/apiaryio/dredd/builds/$TRAVIS_BUILD_ID\"}"
    'https://api.github.com/repos/apiaryio/dredd/statuses/659c3ba8476db3b3317a377a89b370fd35a8e2bc'
  - >-
    if [[ $TRAVIS_BRANCH = master ]]; then echo "Deleting aborted (master)" &&
    exit 1; fi
  - git branch -D $TRAVIS_BRANCH
  - >-
    git remote set-url origin
    "https://$GITHUB_TOKEN@github.com/apiaryio/dredd.git" > /dev/null 2>&1
  - git push origin -f --delete $TRAVIS_BRANCH > /dev/null 2>&1
